#! /bin/sh
# When invoked with the right arguments, a minimal help message should be echoed to stderr.

TESTNAME=$1
ARG=$2  # may be empty
EXPECTED_EXIT_CODE=$3

ERR=$TMPDIR/$(basename $TESTNAME).err

. $TESTDIR/lib_test_functions

$BINDIR/opm $ARG 2> $ERR
check_exit_code $? $EXPECTED_EXIT_CODE

PATTERN="Usage.*subcommand"
if grep -q $PATTERN $ERR; then :; else
  echo $0 $ARG No usage text found >> $LOGFILE
  cat $ERR >> $LOGFILE
  exit 1
fi

echo "$0 $ARG found expected usage text:" >> $LOGFILE
grep $PATTERN $ERR >> $LOGFILE

exit 0
