#! /bin/sh
# Running 'opm list package' should show that package if it is installed and nothing if it is not

. $TESTDIR/lib_packages
. $TESTDIR/lib_test_functions

ERR=$TMPDIR/$(basename $0).err
OUT=$TMPDIR/$(basename $0).out

run_apt_get_update_on_debian

PACKAGE_1=$(echo "$INSTALLED_PACKAGES" | cut -d ' ' -f 1)
PACKAGE_2=$(echo "$INSTALLED_PACKAGES" | cut -d ' ' -f 2)
$BINDIR/opm list $PACKAGE_1 $PACKAGE_2 > $OUT 2> $ERR
EXIT_CODE=$?

copy_file_to_log $OUT stdout
copy_file_to_log $ERR stderr
check_exit_code $EXIT_CODE 0

for package in $PACKAGE_1 $PACKAGE_2; do
  if ! grep -q "^$package" $OUT; then
    echo Failed to find $package in output >> $LOGFILE
    exit 1
  fi
done

ANOTHER_INSTALLED_PACKAGE=$(echo "$INSTALLED_PACKAGES" | cut -d ' ' -f 3)
ONE_UNINSTALLED_PACKAGE=$(echo "$INSTALLABLE_PACKAGES" | cut -d ' ' -f 1)
for package in $ANOTHER_INSTALLED_PACKAGE $ONE_UNINSTALLED_PACKAGE; do
  if grep -q "^$package" $OUT; then
    echo Found unexpected package $package in output >> $LOGFILE
    exit 1
  fi
done

exit 0
