#! /bin/sh
# Running `opm help`, `opm help -h`, `opm help --help` and `opm help help` should all give the same argument

. $TESTDIR/lib_test_functions

ERR=$TMPDIR/$(basename $0).err
OUT=$TMPDIR/$(basename $0).out

run_happy_case_command_variant 1 $BINDIR/opm help
run_happy_case_command_variant 2 $BINDIR/opm help -h
run_happy_case_command_variant 3 $BINDIR/opm help --help
run_happy_case_command_variant 4 $BINDIR/opm help help

check_files_are_equal ${OUT}.1 ${OUT}.2
check_files_are_equal ${OUT}.1 ${OUT}.3
check_files_are_equal ${OUT}.1 ${OUT}.4
