#! /bin/sh
# Running `opm install package` installs that package

. $TESTDIR/lib_test_functions

ERR=$TMPDIR/$(basename $0).err
OUT=$TMPDIR/$(basename $0).out

if [ $(uname) = Darwin ]; then
  . $TESTDIR/lib_macos
  for package in $MACOS_INSTALLABLE_PACKAGES; do
    if brew list "$package" > /dev/null 2>&1; then
      # Package is already installed
      continue
    fi

    $BINDIR/opm install $package > $OUT 2> $ERR
    EXIT_CODE=$?

    copy_file_to_log $OUT stdout
    copy_file_to_log $ERR stderr

    check_exit_code $EXIT_CODE 0

    if brew list "$package" > /dev/null 2>&1; then
      # Installation looks to have been successful

      brew uninstall $package > /dev/null 2>&1
    else
      echo "opm install $package failed" >> $LOGFILE
      exit 1
    fi

    exit 0
  done

  echo "Could not find a package to install - everything attempted was already installed" >> $LOGFILE
  exit 1
else
  . $TESTDIR/lib_linux
  run_apt_get_update_on_debian

  package=$(echo $LINUX_INSTALLABLE_PACKAGES | sed 's/ .*//')  # just take the first one
  if $BINDIR/opm list 2> /dev/null | grep "^${package}\>" > /dev/null; then
    echo $package is already installed before test starts >> $LOGFILE
    exit 1
  fi

  $BINDIR/opm install $package > $OUT 2> $ERR
  EXIT_CODE=$?

  copy_file_to_log $OUT stdout
  copy_file_to_log $ERR stderr

  check_exit_code $EXIT_CODE 0

  if $BINDIR/opm list 2> /dev/null | grep "^${package}\>" > /dev/null; then
    # Installation looks to have been successful
    $BINDIR/opm uninstall $package > /dev/null 2>&1  # not part of the test, so ignore whether it works or not
  else
    echo "opm install $package failed" >> $LOGFILE
    exit 1
  fi

  exit 0
fi
