#! /bin/sh
# Running help for an unrecognised subcommand should report an error and exit non-zero

. $TESTDIR/lib_test_functions

ERR=$TMPDIR/$(basename $0).err
OUT=$TMPDIR/$(basename $0).out

$BINDIR/opm help nosuchcommand > $OUT 2> $ERR
EXIT_CODE=$?

check_exit_code $EXIT_CODE 1

check_file_is_empty $OUT stdout
check_file_is_not_empty $ERR stderr
