#! /bin/sh
# opm list without finding a valid package manager writes to stderr and exits non-zero

. $TESTDIR/lib_test_functions.sh

ERR=$TMPDIR/$(basename $0).err
OUT=$TMPDIR/$(basename $0).out

# Debian has apt in /usr/bin, so hide it for the duration of
# running `opm list`
[ $(uname) = Linux -a -f /usr/bin/apt ] && mv /usr/bin/apt /usr/bin/apt.bak
PATH=/bin:/usr/bin $BINDIR/opm list > $OUT 2> $ERR
CODE=$?
[ -f /usr/bin/apt.bak ] && mv /usr/bin/apt.bak /usr/bin/apt

check_file_is_empty "$OUT" stdout

check_file_is_not_empty "$ERR" stderr

check_exit_code $CODE 1

exit 0
