#! /bin/sh
# Runnning `opm help install`, `opm install` (without arguments), `opm install -h` and `opm install --help` all provide a Usage message

. $TESTDIR/lib_test_functions

ERR=$TMPDIR/$(basename $0).err
OUT=$TMPDIR/$(basename $0).out

run_happy_case_command_variant 1 $BINDIR/opm help install
run_happy_case_command_variant 2 $BINDIR/opm install
run_happy_case_command_variant 3 $BINDIR/opm install -h
run_happy_case_command_variant 4 $BINDIR/opm install --help

if ! grep -q ^Usage ${OUT}.1; then
  echo Usage message not found in output >> $LOGFILE
  exit $EXIT_TEST_FAILED
fi

check_files_are_equal ${OUT}.1 ${OUT}.2
check_files_are_equal ${OUT}.1 ${OUT}.3
check_files_are_equal ${OUT}.1 ${OUT}.4
