#! /bin/sh
# Running list subcommand should result in a list of installed packages

ERR=$TMPDIR/test3.err
OUT=$TMPDIR/test3.out

$BINDIR/opm list > $OUT 2> $ERR

if [ $(uname) = Darwin ]; then
  # This is awkward: there are no guarantees about what will be installed.
  # For now, be happy with *something* on stdout and nothing written to stderr
  if [ -z "$(cat $OUT)" -o -n "$(cat $ERR)" ]; then
    echo "$0 No output on stdout or unexpected output on stderr" >> $LOGFILE
    echo "--- begin stderr ---" >> $LOGFILE
    cat $ERR >> $LOGFILE
    echo "--- end stderr ---" >> $LOGFILE
    exit 1
  fi
else
  if [ -f /etc/alpine-release ]; then
    expected_package=busybox
  elif [ -f /etc/debian_version ]; then
    # Debian or Ubuntu
    expected_package=debianutils
  else
    echo "$0 Unrecognised OS encountered" >> $LOGFILE
    exit 1
  fi

  if grep -q "^${expected_package}.*installed" $OUT; then
    # All good
    :
  else
    echo "$0 Expected package $expected_package not found" >> $LOGFILE
    echo "--- begin stdout ---" >> $LOGFILE
    cat $OUT >> $LOGFILE
    echo "--- end stdout ---" >> $LOGFILE
    exit 1
  fi
fi
