#! /bin/sh
# opm list without finding a valid package manager writes to stderr and exits non-zero

. $TESTDIR/lib_test_functions

ERR=$TMPDIR/$(basename $0).err
OUT=$TMPDIR/$(basename $0).out

# Debian has apt in /usr/bin, so hide it for the duration of
# running `opm list`; ditto rpm/yum/microdnf on Oracle Linux,
# and pacman on arch.
if [ $(uname) = Linux ]; then
  FILES_TO_HIDE="/usr/bin/apt /usr/bin/rpm /usr/bin/yum /usr/bin/microdnf /usr/bin/pacman"
  for f in $FILES_TO_HIDE; do
    if [ -f "$f" ]; then
      mv $f ${f}.bak
    fi
  done
fi

PATH=/bin:/usr/bin $BINDIR/opm list > $OUT 2> $ERR
CODE=$?

for f in $FILES_TO_HIDE; do
  if [ -f "${f}.bak" ]; then
    mv "${f}.bak" "$f"
  fi
done

copy_file_to_log "$ERR" stderr

check_file_is_empty "$OUT" stdout

check_file_is_not_empty "$ERR" stderr

check_exit_code $CODE 1

exit $EXIT_TEST_PASSED
