#! /bin/sh
# Running help subcommand should result in a list of subcommands

. $TESTDIR/lib_test_functions

OUT=$TMPDIR/$(basename $0).out

$BINDIR/opm help > $OUT

for expected_subcmd in help install list uninstall; do
  awk -v cmd=$expected_subcmd '($1 == cmd) {found=1; print "Found expected subcommand " cmd ":"; print;} END {if (found) exit 0; else exit 1}' $OUT >> $LOGFILE

  if [ $? != 0 ]; then
    echo Subcommand $expected_subcmd not found in output >> $LOGFILE
    copy_file_to_log $OUT output
    exit 1
  fi
done

exit 0
