#! /bin/sh

short_help() {
  echo "Usage: $0 [OPTIONS] subcommand"
  echo "See  $0 help  to list available commands"
}

if [ -z "$1" -o "$1" = "-h" -o "$1" = "--help" ]; then
  short_help > /dev/stderr
  [ -z "$1" ] && code=1 || code=0
  exit $code
fi

# TODO: Global arguments before subcommand

lookup_alias() {
  # look up $cmd in the aliases file and, if found, update $cmd and $subfile then return 0
  # return 1 if not found
  while read alias alias_for; do
    if [ "$alias" = "$cmd" ]; then
      cmd=$alias_for
      subfile="${src_dir}/opm_$cmd"
      if [ ! -x "$subfile" ]; then
        echo "Corrupt install: $alias expands to $alias_for, but $subfile is not executable" > /dev/stderr
        exit 1
      fi
      return 0
    fi
  done < ${src_dir}/opm.aliases
  return 1
}

cmd=$1
shift
src_dir=$(dirname $0)
subfile="${src_dir}/opm_$cmd"
if [ ! -x "$subfile" ]; then
  if ! lookup_alias; then
    echo "Unrecognised subcommand '$cmd'."
    echo "See   $0 help   to list available commands"
    exit 1
  fi
fi

exec "$subfile" "$@"
