#! /bin/sh
# opm uninstall: Uninstall one or more packages

if [ "$1" = "--list-commands" ]; then
  printf "  %-10s Uninstall one or more packages\n"  uninstall
  exit 0
fi

if [ -z "$1" -o "$1" = "-h" -o "$1" = "--help" ]; then
  echo Usage: opm uninstall package...
  exit 0
fi

assume_yes=false
if [ "$1" = "-y" -o "$1" = "--yes" ]; then
  assume_yes=true
  shift
fi

# try_FOO -
#   if package manager FOO is found:
#     invoke the package manager to uninstall the package(s) specified on the command line
#     set EXIT_CODE
#     return 0
#   otherwise, return 1

try_apk() {
  if [ -x "$(command -v apk)" ]; then
    apk del --no-interactive "$@"
    EXIT_CODE=$?
    return 0
  fi
  return 1
}

try_aptget() {
  if [ -x "$(command -v apt-get)" ]; then
    apt-get remove --yes "$@"
    EXIT_CODE=$?
    return 0
  fi
  return 1
}

try_brew() {
  if [ -x "$(command -v brew)" ]; then
    brew uninstall "$@"
    EXIT_CODE=$?
    return 0
  fi
  return 1
}

try_microdnf() {
  if [ -x "$(command -v microdnf)" ]; then
    local microdnf_opts
    if $assume_yes; then
      microdnf_opts=-y
    fi
    microdnf remove $microdnf_opts "$@"
    EXIT_CODE=$?
    return 0
  fi
  return 1
}

try_pacman() {
  if [ -x "$(command -v pacman)" ]; then
    local pacman_opts
    if $assume_yes; then
      pacman_opts=--noconfirm
    fi
    pacman -R $pacman_opts "$@"
    EXIT_CODE=$?
    return 0
  fi
  return 1
}

try_yum() {
  if [ -x "$(command -v yum)" ]; then
    local yum_opts
    if $assume_yes; then
      yum_opts=-y
    fi
    yum remove $yum_opts "$@"
    EXIT_CODE=$?
    return 0
  fi
  return 1
}

if [ $(uname) = Darwin ]; then
  try_brew "$@" && exit $EXIT_CODE
else
  try_apk "$@" && exit $EXIT_CODE
  try_aptget "$@" && exit $EXIT_CODE
  try_microdnf "$@" && exit $EXIT_CODE
  try_pacman "$@" && exit $EXIT_CODE
  try_yum "$@" && exit $EXIT_CODE
  try_brew "$@" && exit $EXIT_CODE
fi

echo No supported package manager installed >&2
exit 1
