#! /bin/sh
# opm list: list install packages

if [ "$1" = "--list-commands" ]; then
  printf "  %-10s list installed packages\n"  list
  exit 0
fi

if [ "$1" = "-h" -o "$1" = "--help" ]; then
  echo list help
  exit 0
fi

# check for brew before apt, because macOS has a Java tool apt
if [ -x "$(command -v apk)" ]; then
  apk list --installed
elif [ -x "$(command -v brew)" ]; then
  brew list
elif [ -x "$(command -v apt)" ]; then
  apt list --installed
else
  echo No supported package manager installed
fi
