#! /bin/sh
# opm uninstall: Uninstall one or more packages

if [ "$1" = "--list-commands" ]; then
  printf "  %-10s Uninstall one or more packages\n"  uninstall
  exit 0
fi

if [ -z "$1" -o "$1" = "-h" -o "$1" = "--help" ]; then
  echo Usage: opm uninstall package...
  exit 0
fi

echo TODO
