#! /bin/sh
# opm list: list install packages

if [ "$1" = "--list-commands" ]; then
  printf "  %-10s list installed packages\n"  list
  exit 0
fi

if [ "$1" = "-h" -o "$1" = "--help" ]; then
  echo list help
  exit 0
fi

# try_FOO -
#   if package manager FOO is found: 
#     invoke the package manager to list installed packages
#     set EXIT_CODE
#     return 0
#   otherwise, return 1

try_apk() {
  if [ -x "$(command -v apk)" ]; then
    apk list --installed
    EXIT_CODE=$?
    return 0
  fi
  return 1
}

try_apt() {
  if [ -x "$(command -v apt)" ]; then
    apt list --installed
    EXIT_CODE=$?
    return 0
  fi
  return 1
}

try_brew() {
  if [ -x "$(command -v brew)" ]; then
    brew list
    EXIT_CODE=$?
    return 0
  fi
  return 1
}

if [ $(uname) = Darwin ]; then
  try_brew && exit $EXIT_CODE
else
  try_apk && exit $EXIT_CODE
  try_apt && exit $EXIT_CODE
  try_brew && exit $EXIT_CODE
fi

echo No supported package manager installed >&2
exit 1
